### PR TITLE
Add/edit book refactor and restyle

### PR DESCRIPTION
**Pull request by imswebra**
- **Refactors `addBookActivity.java` and `editBookActivity.java` to inherit from a common `addEditBookActivity.java` class**
  - Showcases a simple pattern that can be used by others. Allows for different layouts between subclasses, doesn't break theming, and allows superclass to reference elements from the same layout instance as the subclass.
- **Refactors `activity_add_book.xml` and `activity_edit_book.xml` to use common components from a new `components_add_edit_book.xml` layout file.**
  - Showcases the pattern of using `<include>` to abstract layouts. See `<merge>` also if you are using linear layouts.
- **Overhauls all the add/edit book activities and layouts to use the material design components and look pretty (matching what we have in Figma, with some slight adjustments).**
- **Updates the add/edit book layouts to be properly responsive (using constrainLayout!) and screen-size independent**
  - All size hardcoding (aside from margins/padding) has been removed
  - Book image now is fixed to a 1:1 aspect ratio
  - By default, the book image's width (and thus height) will now be ~60% of the phone's width (not exact because of margin/padding) and the image will center itself between the description input and the bottom buttons. As the distance between these two views is decreased (due to a smaller phone or a growing multi-line description), this centering is maintained, with just the whitespace above and below the image decreasing. Once said whitespace reaches zero, the book image itself will begin to scale down. During this scaling, the 1:1 aspect ratio is maintained. The size of the delete image button is not scaled (to keep it tapable), but it does move to match the position of the image's top right corner.
- **Adds a number of definitions that can be used by other devs for their various activities:**
  - `components_book_image_card.xml` layout which provides an image card with rounded corners and a 1:1 aspect ratio
     - @nayancprakash This should be used in the book details pages, though it's use doesn't need to be exactly the same as I have it for the add/edit stuff because we shouldn't need fancy image scaling (I don't think).
  - `color/deny` for the red seen in Figma
    - @nayancprakash @ryankortbeek This should be used in the mange requests page for the reject button
  - `style/OutlinedSpacedTextInputLayout` and derivatives for consistently spacing our text inputs
    - @KonradStanski The sign-up and edit profile layouts should be updated to use this so we can tweak the exact spacing and such in one place. Note that your text inputs will all have to be chained to get proper margin addition if you are using ConstrainLayout.
  - `style/BottomButton` for buttons anchored to the bottom of the screen. Extremely trivial, but it will be nice to have if we ever want to tweak that spacing from the bottom.
    - @nayancprakash for the book details pages, @KonradStanski for the sign-up and edit profile pages

Tests have been updated appropriately, but nothing has been added as there is no additional functionality. After merge, I'll be responsible for updating the UI mock and the UML diagram accordingly.

### CODE REVIEW

**Review by kylehennig — APPROVED** [review]
Happy to see so much duplicate code being eliminated via inheritance. Approved.

**Comment by KonradStanski** [comment]
> * using constrainLayout!

Using constraint layout!?!

**Comment by imswebra** [comment]
> Using constraint layout!?!
@KonradStanski 

It's true! I still stand by linear layout for easy things, but the image scaling widget scaling was definitely not that.

**Comment by mitchadam** [comment]
Nice, I will update my other screens to match.

**Pull request merged**
